apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-uvad
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-uvad
    app.kubernetes.io/part-of: test-app-gewb
  name: test-component-uvad
  namespace: build-templates-e2e
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-uvad
status:
  loadBalancer: {}
